---
- name: Install nginx
  hosts: centos_nodes,ubuntu_nodes
  become: yes

  tasks:
    - name: Install nginx
      package:
        name: nginx
        state: latest
    - name: Start nginx service
      service:
        name: nginx
        state: started
        enabled: yes